name: Build & Deploy Doxygen

on:
  push:
    branches: [ main ]

jobs:
  doxygen:
    runs-on: ghcr.io/doxygen/doxygen:1.12.0
    steps:
      - uses: actions/checkout@v3
        with:
            submodules: recursive
      - name: Build docs
        run: |
          doxygen --version
          doxygen Doxyfile
          # ensure nojekyll so assets like underscore-files aren’t ignored
          touch .nojekyll
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/html
          publish_branch: gh-pages
